# Generated by Django 5.2.13 on 2026-05-04 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('media_type', models.CharField(choices=[('movie', '电影'), ('book', '书籍'), ('game', '游戏'), ('music', '音乐'), ('drama', '剧集')], max_length=10, verbose_name='类型')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='media_covers/%Y/%m/', verbose_name='封面')),
                ('rating', models.PositiveSmallIntegerField(default=0, help_text='0-10 分，对应 0-5 星', verbose_name='评分')),
                ('creator', models.CharField(blank=True, help_text='导演/作者/开发商等', max_length=200, verbose_name='创作者')),
                ('summary', models.TextField(blank=True, verbose_name='简评')),
                ('status', models.CharField(choices=[('done', '已看/已读/已玩'), ('doing', '在看/在读/在玩'), ('wish', '想看/想读/想玩')], default='done', max_length=10, verbose_name='状态')),
                ('finished_date', models.DateField(blank=True, null=True, verbose_name='完成日期')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '书影音',
                'verbose_name_plural': '书影音',
                'ordering': ['-finished_date', '-created_time'],
            },
        ),
    ]
