# Generated by Django 5.2.13 on 2026-05-04 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='douban_url',
            field=models.URLField(blank=True, verbose_name='豆瓣链接'),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(choices=[('movie', '影视'), ('book', '书籍'), ('game', '游戏')], max_length=10, verbose_name='类型'),
        ),
    ]
