# Generated by Django 5.2.13 on 2026-05-04 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_media_douban_url_alter_media_media_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='站点名称')),
                ('url', models.URLField(verbose_name='链接')),
                ('avatar', models.URLField(blank=True, verbose_name='头像链接')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='描述')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '友链',
                'verbose_name_plural': '友链',
                'ordering': ['sort_order', '-pk'],
            },
        ),
    ]
