# Generated by Django 5.2.13 on 2026-05-04 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone
from django.utils.text import slugify


def populate_slug_and_approve_comments(apps, schema_editor):
    Post = apps.get_model('blog', 'Post')
    Comment = apps.get_model('blog', 'Comment')

    used = set(Post.objects.exclude(slug='').values_list('slug', flat=True))
    for post in Post.objects.order_by('pk'):
        base_slug = slugify(post.title, allow_unicode=True)[:90] or (f'post-{post.pk}' if post.pk else f'post-{timezone.now():%Y%m%d%H%M%S}')
        slug = base_slug
        suffix = 2
        while slug in used:
            suffix_text = f'-{suffix}'
            slug = f'{base_slug[:120 - len(suffix_text)]}{suffix_text}'
            suffix += 1
        post.slug = slug
        post.save(update_fields=['slug'])
        used.add(slug)

    Comment.objects.filter(status='pending').update(status='approved')


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_add_article_toc_demo_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('hidden', '已隐藏')], db_index=True, default='pending', max_length=20, verbose_name='审核状态'),
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, db_index=False, max_length=120, verbose_name='Slug'),
        ),
        migrations.RunPython(populate_slug_and_approve_comments, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=120, unique=True, verbose_name='Slug'),
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '新增'), ('update', '修改'), ('delete', '删除'), ('review', '审核'), ('backup', '备份'), ('restore', '恢复')], max_length=20, verbose_name='操作类型')),
                ('object_type', models.CharField(max_length=100, verbose_name='对象类型')),
                ('object_id', models.CharField(blank=True, max_length=64, verbose_name='对象 ID')),
                ('object_repr', models.CharField(max_length=255, verbose_name='对象名称')),
                ('detail', models.TextField(blank=True, verbose_name='详情')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'ordering': ['-created_time'],
            },
        ),
    ]
