# Generated by Django 5.2.13 on 2026-05-04 19:33

import django.utils.timezone
from django.db import migrations, models


def copy_created_time_to_publish_time(apps, schema_editor):
    Post = apps.get_model('blog', 'Post')
    for post in Post.objects.all().only('pk', 'created_time'):
        post.publish_time = post.created_time
        post.save(update_fields=['publish_time'])


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_comment_spam_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.AddField(
            model_name='post',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='置顶'),
        ),
        migrations.AddField(
            model_name='post',
            name='publish_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='发布时间'),
        ),
        migrations.RunPython(copy_created_time_to_publish_time, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='post',
            name='publish_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间'),
        ),
    ]
