# Generated by Django 5.2.13 on 2026-05-04 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_remove_post_slug_post_is_pinned_post_publish_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={
                'ordering': ['-is_pinned', '-publish_time'],
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
    ]
